# Generated by Django 5.2.4 on 2025-07-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articleId', models.IntegerField()),
                ('articleImg', models.ImageField(upload_to='')),
                ('articleName', models.CharField(max_length=100)),
                ('articleContent', models.TextField()),
                ('publishDate', models.DateField()),
                ('authorId', models.IntegerField()),
            ],
        ),
    ]
